---
-  hosts: slave
   gather_facts: True
   remote_user: sergei

   vars:
     - package_name: "httpd"

   tasks:

     - include: install_apache.yml

     - name: Check apache service
       service: name={{ package_name  }} state=started
       sudo: yes

