---
-  hosts: slave2
   gather_facts: True
   remote_user: sergei

   tasks:

     - name: Copy file remotely
       copy: src=test2.conf dest=/etc/test2.conf owner=root group=root mode=0644
       sudo: yes

