---
-  hosts: slave
   gather_facts: False
   remote_user: sergei
   tasks:

     - name: Install apache package
       apt: name=apache2 state=latest update_cache=yes
       sudo: yes

     - name: Starting apache service
       service: name=apache2 state=started
       sudo: yes
