---
-  hosts: slave2
   gather_facts: True
   remote_user: sergei

   tasks:

     - name: Create a virtual host
       template: src=test.conf dest=/etc/apache2/test.conf mode=644 validate='httpd -t -f %s'
       sudo: yes
